### ISSUE TITLE
Version 1.0 checklist

### ISSUE THREAD

**Issue by pepibumur** [xcbuddy/xcbuddy#24]
## Context 🕵️‍♀️
This issue contains all the work that needs to be done for the first tool release.

## What 🌱
- [ ] Update `Init` command to generate a `Workspace.swift`, `Project.swift` and `Config.swift`.
- [ ] Validate dependencies *(platforms, products, bundle_ids)*
- [ ] Generate `ProjectDescription` target that contains the `.swift` manifests.
- [ ] Add a launch check that fails the execution if the version of Swift in the system is not compatible with the version of Swift the frameworks were compiled with.
- [ ] Framework embedder.
- [ ] Add version command.
- [ ] Fix auto-updater not working.
- [ ] Implement macOS application.
